org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

# Environment Properties
minecraft_version=26.2
minecraft_version_range=[26.1.2, 27.0)
neo_version=26.2.0.64
neo_version_range=[26.1.0,)
loader_version_range=[4,)

## Mod Properties
mod_id=maizemod
mod_name=Maize Mod
mod_license=All Rights Reserved
mod_version=1.0.0
mod_group_id=nicusha.maize
mod_authors=Nicusha
mod_description=This mod adds corn
mod_url=https://legacy.curseforge.com/minecraft/mc-mods/maize-mod
mod_logo=logo.png
mod_banner=banner.png
issue_tracker_url=https://github.com/NicosaurusRex99/Maize/issues
mod_update_json=https://raw.githubusercontent.com/NicosaurusRex99/Nicusha-mod-assets/refs/heads/main/maize_update.json

## Dependencies
jei_version=30.18.0.144

configured_id=8403595
jer_id=8570081
jei_wg_id=8549293